name: Deploy Snapshot to Maven Central

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: 'maven'
      - name: Set up npm cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Build and Deploy with Maven
        env:
          JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME: ${{ secrets.SONATYPE_TECHNICAL_USER_NAME }}
          JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD: ${{ secrets.SONATYPE_TECHNICAL_USER_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.OPEN_ELEMENTS_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.OPEN_ELEMENTS_GPG_PRIVATE_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.OPEN_ELEMENTS_GPG_PASSPHRASE }}
          JRELEASER_GITHUB_TOKEN: FOOBAR
        run: ./mvnw -Pdeploy clean deploy && ./mvnw jreleaser:deploy
