name: Deploy main frontend to Azure

env:
  AZURE_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BENCHSCAPE_MAIN }}
  JAVA_VERSION: '17'
  DISTRIBUTION: temurin
  APP_LOCATION: "jmh-frontend/src/main/frontend/build"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn verify

      - name: Upload
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: ${{ env.APP_LOCATION }}
