name: Publish integration server image

env:
  IMAGE_NAME: benchscape-integration-server
  CONTEXT: ./server/

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app
          labels: |
            org.opencontainers.image.title=BenchScape server
            org.opencontainers.image.description=Server image for BenchScape
            org.opencontainers.image.source=https://github.com/OpenElements/BenchScape
            org.opencontainers.image.licenses=APACHE 2
            org.opencontainers.image.vendor=Open Elements
            org.opencontainers.image.authors=Open Elements
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
            org.opencontainers.image.ref.name=${{ github.sha }}
            profile=integration

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify -P npm-integration-build

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: |
            ghcr.io/openelements/${{ env.IMAGE_NAME }}:latest
            ghcr.io/openelements/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "JAVA_OPTS=-Dspring.profiles.active=integration"
          context: ${{ env.CONTEXT }}
